export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST"
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS"
export const GET_TODOS_ERROR = "GET_TODOS_ERROR"

export const CREATE_TODOS_REQUEST = "CREATE_TODOS_REQUEST"
export const CREATE_TODOS_SUCCESS = "CREATE_TODOS_SUCCESS"
export const CREATE_TODOS_ERROR = "CREATE_TODOS_ERROR"

export const UPDATE_TODOS_REQUEST = "UPDATE_TODOS_REQUEST"
export const UPDATE_TODOS_SUCCESS = "UPDATE_TODOS_SUCCESS"
export const UPDATE_TODOS_ERROR = "UPDATE_TODOS_ERROR"

export const DELETE_TODOS_REQUEST = "DELETE_TODOS_REQUEST"
export const DELETE_TODOS_SUCCESS = "DELETE_TODOS_SUCCESS"
export const DELETE_TODOS_ERROR = "DELETE_TODOS_ERROR"